spring:
  datasource:
    url: jdbc:mysql://mysql:3306/raumania?createDatabaseIfNotExist=true
    username: root
    password: lilyiker

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mail:
    host: smtp.gmail.com
    username: thai382004@gmail.com
    password: "rogt pvyf phua cbpg"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_PORT:9200}

jwt:
  accessExpiryTime: ${JWT_ACCESS_EXPIRY_TIME}
  refreshExpiryTime: ${JWT_REFRESH_EXPIRY_TIME}
  secretKey: ${JWT_SECRET_KEY}
  refreshKey: ${JWT_REFRESH_KEY}

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecret: ${STRIPE_WEBHOOK_SECRET}
  successUrl: ${frontend.url}/payment-success?session_id={CHECKOUT_SESSION_ID}
  cancelUrl: ${frontend.url}/api/stripe/cancelled

frontend:
  url: ${FRONTEND_URL}

chatbot:
  url: ${CHATBOT_URL}


